### PR TITLE
Updated file-coding and text

### PR DESCRIPTION
**Pull request by dunahan**
As above, updated my file to be encoded in Western (ISO 8859-15) and changed lines 32/33 and 62/63 to show correctly. Also added translations at line 68/69 due line 62/63 could be too long.

### CODE REVIEW

**Comment by tinygiant98** [comment]
Thanks, will look at this tonight after work.

**Review by tinygiant98 — CHANGES_REQUESTED** [review]
When `NEXT_LABEL` and `PREVIOUS_LABEL` are left as empty strings (`""`), the system will create a label from `NEXT` + `MODEL` and `PREVIOUS` + `MODEL`.

If you're not planning on shortening the `NEXT_LABEL` and `PREVIOUS_LABEL` string values, leave them as empty strings.  In this case, it would have the same result.  If you want to have shorter strings for the labels, I would suggest a value such as `string NEXT_LABEL = NEXT + " >"; ` or similar simplifications, as is used in the russian language file.

Request you either select a different set of values for `NEXT_LABEL` and `PREVIOUS_LABEL` or set them as empty strings because the current values will have the same result as leaving them as empty strings.

**Comment by dunahan** [comment]
I thought so, but wasn't sure. I'll change the ''NEXT_LABEL'' and ''PREVIOUS_LABEL'' like in the russian translation, because in german it would be to long to show properly.

Ah, don't know how to change this commit to show only the right one... I hope that doesn't mess up. If it would, we can close it and I'll do another commit.

**Comment by dunahan** [comment]
Arg, I had time to search the net... When you merge this PR it could delete the file, like it did on my fork... So I'll close it for now and open a new one with the right file... I don't want to mess up something in your master ;)

**Pull request closed without merging**
